name: Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: [self-hosted, vossatandem-web]
    environment: voss-test
    steps:
    - name: Build and Deploy
      run: .\Deploy.ps1
